[connections.snowflake]
account = "GXISMDO-VNB58802"
user = "KD1307"
password = "Bhschool@12345"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
